"""Initial schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2024-12-29 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('plaid_access_token', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_user_id', 'users', ['id'], unique=False)

    op.create_table('brokerages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brokerages_id', 'brokerages', ['id'], unique=False)
    op.create_index('ix_brokerages_user_id', 'brokerages', ['user_id'], unique=False)
    op.create_index('idx_brokerages_user_id', 'brokerages', ['user_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brokerage_id', sa.Integer(), nullable=True),
    sa.Column('plaid_account_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(15, 2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brokerage_id'], ['brokerages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id')
    )
    op.create_index('ix_accounts_id', 'accounts', ['id'], unique=False)
    op.create_index('ix_accounts_user_id', 'accounts', ['user_id'], unique=False)
    op.create_index('ix_accounts_brokerage_id', 'accounts', ['brokerage_id'], unique=False)
    op.create_index('idx_accounts_user_id', 'accounts', ['user_id'], unique=False)
    op.create_index('idx_accounts_brokerage_id', 'accounts', ['brokerage_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('shares', sa.Numeric(15, 6), nullable=False),
    sa.Column('cost_basis', sa.Numeric(15, 2), nullable=False),
    sa.Column('market_value', sa.Numeric(15, 2), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_id', 'positions', ['id'], unique=False)
    op.create_index('ix_positions_user_id', 'positions', ['user_id'], unique=False)
    op.create_index('ix_positions_account_id', 'positions', ['account_id'], unique=False)
    op.create_index('ix_positions_ticker', 'positions', ['ticker'], unique=False)
    op.create_index('idx_positions_user_id', 'positions', ['user_id'], unique=False)
    op.create_index('idx_positions_ticker', 'positions', ['ticker'], unique=False)
    op.create_index('idx_positions_account_id', 'positions', ['account_id'], unique=False)
    op.create_index('idx_positions_snapshot_timestamp', 'positions', ['snapshot_timestamp'], unique=False)

    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(15, 4), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dividend_per_share', sa.Numeric(10, 4), nullable=True),
    sa.Column('shares_at_ex_date', sa.Numeric(15, 6), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dividends_id', 'dividends', ['id'], unique=False)
    op.create_index('ix_dividends_user_id', 'dividends', ['user_id'], unique=False)
    op.create_index('ix_dividends_position_id', 'dividends', ['position_id'], unique=False)
    op.create_index('ix_dividends_ticker', 'dividends', ['ticker'], unique=False)
    op.create_index('idx_dividends_user_id', 'dividends', ['user_id'], unique=False)
    op.create_index('idx_dividends_ticker', 'dividends', ['ticker'], unique=False)
    op.create_index('idx_dividends_pay_date', 'dividends', ['pay_date'], unique=False)
    op.create_index('idx_dividends_status', 'dividends', ['status'], unique=False)

    op.create_table('ex_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('dividend_amount', sa.String(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', 'ex_date', name='uq_ex_dates_user_ticker_date')
    )
    op.create_index('ix_ex_dates_id', 'ex_dates', ['id'], unique=False)
    op.create_index('ix_ex_dates_user_id', 'ex_dates', ['user_id'], unique=False)
    op.create_index('ix_ex_dates_ticker', 'ex_dates', ['ticker'], unique=False)
    op.create_index('ix_ex_dates_ex_date', 'ex_dates', ['ex_date'], unique=False)
    op.create_index('idx_ex_dates_user_id', 'ex_dates', ['user_id'], unique=False)
    op.create_index('idx_ex_dates_ticker', 'ex_dates', ['ticker'], unique=False)
    op.create_index('idx_ex_dates_ex_date', 'ex_dates', ['ex_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ex_dates_ex_date', table_name='ex_dates')
    op.drop_index('idx_ex_dates_ticker', table_name='ex_dates')
    op.drop_index('idx_ex_dates_user_id', table_name='ex_dates')
    op.drop_index('ix_ex_dates_ex_date', table_name='ex_dates')
    op.drop_index('ix_ex_dates_ticker', table_name='ex_dates')
    op.drop_index('ix_ex_dates_user_id', table_name='ex_dates')
    op.drop_index('ix_ex_dates_id', table_name='ex_dates')
    op.drop_table('ex_dates')
    op.drop_index('idx_dividends_status', table_name='dividends')
    op.drop_index('idx_dividends_pay_date', table_name='dividends')
    op.drop_index('idx_dividends_ticker', table_name='dividends')
    op.drop_index('idx_dividends_user_id', table_name='dividends')
    op.drop_index('ix_dividends_ticker', table_name='dividends')
    op.drop_index('ix_dividends_position_id', table_name='dividends')
    op.drop_index('ix_dividends_user_id', table_name='dividends')
    op.drop_index('ix_dividends_id', table_name='dividends')
    op.drop_table('dividends')
    op.drop_index('idx_positions_snapshot_timestamp', table_name='positions')
    op.drop_index('idx_positions_account_id', table_name='positions')
    op.drop_index('idx_positions_ticker', table_name='positions')
    op.drop_index('idx_positions_user_id', table_name='positions')
    op.drop_index('ix_positions_ticker', table_name='positions')
    op.drop_index('ix_positions_account_id', table_name='positions')
    op.drop_index('ix_positions_user_id', table_name='positions')
    op.drop_index('ix_positions_id', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_accounts_brokerage_id', table_name='accounts')
    op.drop_index('idx_accounts_user_id', table_name='accounts')
    op.drop_index('ix_accounts_brokerage_id', table_name='accounts')
    op.drop_index('ix_accounts_user_id', table_name='accounts')
    op.drop_index('ix_accounts_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('idx_brokerages_user_id', table_name='brokerages')
    op.drop_index('ix_brokerages_user_id', table_name='brokerages')
    op.drop_index('ix_brokerages_id', table_name='brokerages')
    op.drop_table('brokerages')
    op.drop_index('idx_users_user_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

